### ISSUE TITLE
Error in CvtColor (); function

### ISSUE THREAD

**Issue by Arunsid** [ori-mrg/robotcar-dataset-sdk#14]
Hi Robotcar Dataset Team,

I am using the Robotcar dataset in Opencv ,vsual studio.I have got problem in the conversion of the Raw bayer stereo image(pattern='gbrg' ) to Mat rgb image( cvtColor(); ).

Mat image(height,width, CV_8UC1, Scalar(0,0,255));
image = imread("C:\\Users\\u20w21\\Desktop\\bayer.png");
Mat image2;
cvtColor( image, image2, COLOR_BayerRG2RGB)
...........

<img width="610" alt="error demosaic" src="https://user-images.githubusercontent.com/36816888/39039504-e873c43a-4485-11e8-86c8-22e4d88bc475.png">

But i get an error with cv::demosaic function.Could you please help me with the problem.

**Comment by mttgdd** [comment]
Hi, I am closing this issue as the SDK is only concerned with Python and Matlab tools. If you can reproduce the error using Python OpenCV then please feel free to open the issue again.
