### ISSUE TITLE
How to get RGB images from  Bayer format?

### ISSUE THREAD

**Issue by redhat12345** [ori-mrg/robotcar-dataset-sdk#15]
Using play_images.py, I can see the RGB images. How can I save this images into another folder? Please let me know. Thank you so much.

**Comment by mahfujau** [comment]
Add this line in play_images.py file
`Image.fromarray(img).save('/media/usr//test/' + tokens[0] + '.png')`

**Comment by mahfuj9346449** [comment]
Add the following line:

```
    img = Image.fromarray(img)
    img.save('/media/mahfuj/DATA/ALL_DATASETS/cardataset_oxford/sample/stereo/test/' + tokens[0] + '.png')
```

**Comment by VPRzhou** [comment]
@mahfuj9346449 
I followed your instruction,but there was something wrong happened.The error was shown below:
Traceback (most recent call last):
  File "play_images.py", line 65, in <module>
    img = Image.fromarray(img)
NameError: name 'Image' is not defined
Looking forward your reply.
