### ISSUE TITLE
Does anybody knows the length of the checkerboard for calibration?

### ISSUE THREAD

**Issue by hggaoq** [ori-mrg/robotcar-dataset-sdk#16]
As the checkerboard sequences for calibration of the Grasshopper2 cameras are shown at http://robotcar-dataset.robots.ox.ac.uk/downloads/
Does anybody knows the length of the checkerboard for calibration?

**Comment by mttgdd** [comment]
Hi,
The boards are 115mm by 116.5mm (slightly different length/width), from which it should be easy to divide by the number of squares to get an estimate of the accurate size

**Comment by EXing** [comment]
The checkerboard is 9x7. What does "The boards are 115mm by 116.5mm" mean? It seems not consistent with the calibration image.

**Comment by EXing** [comment]
![1399388191126855](https://user-images.githubusercontent.com/8348898/163359426-6af40e28-abb6-4a25-a815-7147533a9dac.png)
