### ISSUE TITLE
Possible bug in ProjectLaserIntoCamera.m (line 98)

### ISSUE THREAD

**Issue by maunzzz** [ori-mrg/robotcar-dataset-sdk#17]
Hi!
I've tried using ProjectLaserIntoCamera.m on the 2014-12-16-09-14-09 run data  from the dataset but get erroneous results when trying to utilize the visual odometry data.

I'm running the following code:
`root_data_path = 'some_path/oxford/2014-12-16-09-14-09';
image_dir = fullfile(root_data_path,'/mono_left');
laser_dir = fullfile(root_data_path,'/lms_rear');

ins_file = fullfile(root_data_path,'vo/vo.csv');

models_dir = 'some_path/robotcar-dataset-sdk/models';
extrinsics_dir = 'some_path/robotcar-dataset-sdk/extrinsics';
timestamp_file = 'some_path/oxford/2014-12-16-09-14-09/mono_left.timestamps';

timestamps = dlmread(timestamp_file);
timestamp_index = 1800;
image_timestamp = timestamps(timestamp_index,1);

ProjectLaserIntoCamera(image_dir, laser_dir, ins_file, models_dir, extrinsics_dir, image_timestamp)`

which plots this image.
![orig](https://user-images.githubusercontent.com/6471357/46725866-63137d00-cc7d-11e8-89f0-82e2c8843f27.png)

Changing line 98 in ProjectLaserIntoCamera.m instead gives the following results.
![changed](https://user-images.githubusercontent.com/6471357/46725872-673f9a80-cc7d-11e8-8bdd-d8214d746109.png)

Have I done something wrong when calling the function or is there an error in the code?

Thanks,
maunzzz

**Comment by maunzzz** [comment]
I meant to write Changing line 98 in ProjectLaserIntoCamera.m to 

`G_camera_ins = SE3MatrixFromComponents(camera_extrinsics);`

instead gives the following results.

**Comment by mttgdd** [comment]
Hi, firstly sorry for how long it has taken to get to this issue.
The original dataset authors have left the institute and we are trying to maintain the dataset and SDK in perpetuity by giving more time with a different team.
I am seeing this problem too, and I wanted to confirm that the line that you changed was:
```G_camera_ins = eye(4)```
?

**Comment by maunzzz** [comment]
Correct

**Comment by mttgdd** [comment]
Hi again I have managed to replicate the bug and can confirm that the fix you suspected was correct.
I checked the python implementation and it used the camera extrinsics instead of identity matrix
Please see df437d3210339608b838e31fb24164dbea6fcbbc for the fix, which has been pushed to master
