### ISSUE TITLE
How to download ground truth of lane and curb?

### ISSUE THREAD

**Issue by zoukai214** [ori-mrg/robotcar-dataset-sdk#25]
great work! I have finded detection of curbs and lane in [https://www.youtube.com/watch?v=Ski4W2eBh44&t=34s](url),I want to known how to download ground truth of lane and curb?

**Comment by mttgdd** [comment]
Hi, thanks for your interest in our dataset. We do not have/are not aware of/do not provide this type of annotation, unfortunately.
