### ISSUE TITLE
“SyntaxError: invalid syntax” from running the python scripts

### ISSUE THREAD

**Issue by drscopus** [ori-mrg/robotcar-dataset-sdk#26]
I am using python2.7, and the typing-3.7.4.1 package has been installed successfully. 
```
Traceback (most recent call last):
  File "play_radar.py", line 17, in <module>
    from radar import load_radar, radar_polar_to_cartesian
  File "/home/scopus/Downloads/robotcar-dataset-sdk-3.0/python/radar.py", line 20
    def load_radar(example_path: AnyStr) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float]:
                               ^
SyntaxError: invalid syntax
```
Should I use python3? Thanks!

**Comment by mttgdd** [comment]
Hi, that code does indeed look like Python 3.
As Python 2 has now officially reached end of life (https://www.anaconda.com/end-of-life-eol-for-python-2-7-is-coming-are-you-ready/) I would suggest that you use Python 3, yes.
However, as this SDK (besides the radar content) was originally written for Python 2, please do open new issues if you find things that don't work with Python 3.
Thanks!
