### ISSUE TITLE
Errors from running matlab scripts

### ISSUE THREAD

**Issue by drscopus** [ori-mrg/robotcar-dataset-sdk#28]
```
Undefined function or variable 'yticks'.

Error in PlayRadar (line 73)
        yticklabels(azimuths(yticks));
```

I use matlab R2015a in windows 10.

**Comment by mttgdd** [comment]
Hi, based on two searches to archived Matlab documentation for 2015a and then most recent version of Matlab, I think `yticks` is not available in 2015a.

Here is the search for 2015a:
![Screen Shot 2020-01-11 at 11 34 15](https://user-images.githubusercontent.com/3154919/72203668-8d4a8080-3466-11ea-978c-ff05a64dee68.png)


Here is the search for 2019a:
![Screen Shot 2020-01-11 at 11 34 05](https://user-images.githubusercontent.com/3154919/72203663-773cc000-3466-11ea-87f7-fd02361673a0.png)

Based on this, I would suggest if possible that you update your version of Matlab
